//! `analyzer-v2`: Unicode-aware tokenization (S1-T1 acceptance criterion 2).
//!
//! Pipeline per the task's wording ("NFC, case folding, letters/digits by
//! Unicode category, no ASCII-only paths"), with the S1-T14 amendment:
//!   1. NFC-normalize the input (`nfc.normalize`).
//!   2. Split into tokens. A token starts with a letter or digit (General_
//!      Category Lu/Ll/Lt/Lm/Lo, Nd/Nl/No -- `unicode_tables.letter_digit_ranges`)
//!      and continues through letters, digits, the marks attached to them
//!      (Mn/Mc -- `unicode_tables.mark_ranges`) and ZWJ/ZWNJ (U+200D/U+200C)
//!      that are followed by more of the run. Anything else ends the token.
//!      Marks are what write vowels in Tamil, Devanagari, Bengali, Thai, ...:
//!      before S1-T14 they ended a token, so `கணினி` became `கண` and `ன`
//!      and an absent word matched on one-letter fragments. ASCII and Latin
//!      text has no Mn/Mc after NFC (a precomposed `é` is a letter), so its
//!      tokens are unchanged.
//!      S1-T15: variation selectors (U+FE00-FE0F, U+E0100-E01EF) are removed
//!      first, so an emoji keycap `1\u{FE0F}\u{20E3}` tokenizes as `1`.
//!   3. Simple-casefold each codepoint in a run (`unicode_tables.casefold_pairs`).
//!
//! The Python reference (`search_platform.core.tokenize`) implements the same
//! definition with a regex built from the same Mn/Mc table
//! (`search_platform/_marks.py`, generated by `scripts/gen_unicode_tables.py`).
//! This is still not full UAX #29 or grapheme-cluster segmentation: scripts
//! written without spaces (Thai, Khmer, Chinese) remain one run.
//!
//! Documented limitations (ROLES.md: report what is not done, don't hide
//! it):
//! - Case folding here is *simple* (one codepoint to one codepoint), not
//!   Unicode's *full* case folding (which Python's `str.casefold()` uses,
//!   e.g. German sharp s U+00DF -> "ss", some ligatures). This is invisible
//!   for the fixtures this task ships (English and Tamil; Tamil has no
//!   letter case, and the vendored app-text/README fixtures are plain
//!   English prose without sharp-s-style multi-codepoint folds).
//! - NFC (see `nfc.zig`) is complete since S1-T15 (singletons, Hangul) and is
//!   checked against Python over every codepoint by `scripts/nfc_compare.py`.
const std = @import("std");
const nfc = @import("nfc.zig");
const tables = @import("unicode_tables.zig");

pub const analyzer_id = "analyzer-v2";

pub const Error = nfc.Error;

fn inRanges(ranges: []const tables.CodepointRange, cp: u21) bool {
    var lo: usize = 0;
    var hi: usize = ranges.len;
    while (lo < hi) {
        const mid = lo + (hi - lo) / 2;
        const range = ranges[mid];
        if (cp < range.start) {
            hi = mid;
        } else if (cp > range.end) {
            lo = mid + 1;
        } else {
            return true;
        }
    }
    return false;
}

fn isLetterOrDigit(cp: u21) bool {
    return inRanges(&tables.letter_digit_ranges, cp);
}

fn isMark(cp: u21) bool {
    return inRanges(&tables.mark_ranges, cp);
}

fn isJoiner(cp: u21) bool {
    return cp == 0x200C or cp == 0x200D;
}

/// U+FE00..U+FE0F and U+E0100..U+E01EF. Category Mn, but they only choose a
/// glyph (emoji versus text, a CJK variant form), so a token never keeps them
/// and they do not split a token either: `1\u{FE0F}\u{20E3}` is `1`.
fn isVariationSelector(cp: u21) bool {
    return (cp >= 0xFE00 and cp <= 0xFE0F) or (cp >= 0xE0100 and cp <= 0xE01EF);
}

fn casefoldCodepoint(cp: u21) u21 {
    var lo: usize = 0;
    var hi: usize = tables.casefold_pairs.len;
    while (lo < hi) {
        const mid = lo + (hi - lo) / 2;
        const entry = tables.casefold_pairs[mid];
        if (entry.from == cp) return entry.to;
        if (entry.from < cp) lo = mid + 1 else hi = mid;
    }
    return cp;
}

/// Tokenize `text`: NFC-normalize, then split into maximal Unicode
/// letter/digit runs, casefolding each codepoint. Returns an
/// allocator-owned slice of allocator-owned token strings (both freed by
/// freeing the returned slice's elements, then the slice itself, or by
/// using an arena and discarding it wholesale -- the intended use in this
/// codebase, since indexing/query are one-shot CLI operations).
pub fn tokenize(allocator: std.mem.Allocator, text: []const u8) Error![][]const u8 {
    const normalized = try nfc.normalize(allocator, text);
    defer allocator.free(normalized);

    var tokens = std.ArrayList([]const u8).empty;
    defer tokens.deinit(allocator);

    var cps = std.ArrayList(u21).empty;
    defer cps.deinit(allocator);
    var view = std.unicode.Utf8View.init(normalized) catch return error.InvalidUtf8;
    var iterator = view.iterator();
    while (iterator.nextCodepoint()) |cp| {
        if (isVariationSelector(cp)) continue; // S1-T15: presentation only, dropped
        try cps.append(allocator, cp);
    }

    var current = std.ArrayList(u8).empty;
    defer current.deinit(allocator);
    var in_token = false;
    for (cps.items, 0..) |cp, i| {
        const continues = isLetterOrDigit(cp) or (in_token and (isMark(cp) or (isJoiner(cp) and
            i + 1 < cps.items.len and (isLetterOrDigit(cps.items[i + 1]) or isMark(cps.items[i + 1])))));
        if (continues) {
            in_token = true;
            const folded = casefoldCodepoint(cp);
            var buffer: [4]u8 = undefined;
            const len = std.unicode.utf8Encode(folded, &buffer) catch return error.InvalidUtf8;
            try current.appendSlice(allocator, buffer[0..len]);
        } else if (in_token) {
            try tokens.append(allocator, try current.toOwnedSlice(allocator));
            current = std.ArrayList(u8).empty;
            in_token = false;
        }
    }
    if (in_token) {
        try tokens.append(allocator, try current.toOwnedSlice(allocator));
    }
    return tokens.toOwnedSlice(allocator);
}

pub fn freeTokens(allocator: std.mem.Allocator, tokens: [][]const u8) void {
    for (tokens) |token| allocator.free(token);
    allocator.free(tokens);
}

test "tokenize splits, casefolds, and NFC-normalizes English text" {
    const allocator = std.testing.allocator;
    const tokens = try tokenize(allocator, "Zig, search-v2! Cafe\u{0301} rocks.");
    defer freeTokens(allocator, tokens);
    const expected = [_][]const u8{ "zig", "search", "v2", "caf\u{00e9}", "rocks" };
    try std.testing.expectEqual(expected.len, tokens.len);
    for (expected, tokens) |want, got| try std.testing.expectEqualStrings(want, got);
}

fn expectTokens(text: []const u8, expected: []const []const u8) !void {
    const allocator = std.testing.allocator;
    const tokens = try tokenize(allocator, text);
    defer freeTokens(allocator, tokens);
    try std.testing.expectEqual(expected.len, tokens.len);
    for (expected, tokens) |want, got| try std.testing.expectEqualStrings(want, got);
}

test "tokenize keeps Tamil words whole (S1-T14)" {
    try expectTokens("கணினி", &.{"கணினி"});
    try expectTokens("யானைகள்", &.{"யானைகள்"});
    try expectTokens("தமிழ் மொழி", &.{ "தமிழ்", "மொழி" });
    try expectTokens("நான் வீட்டிற்கு போகிறேன்", &.{ "நான்", "வீட்டிற்கு", "போகிறேன்" });
}

test "tokenize keeps Devanagari and Latin-with-accents words whole (S1-T14)" {
    try expectTokens("किताब", &.{"किताब"});
    try expectTokens("café", &.{"café"});
    try expectTokens("Cafe\u{0301}", &.{"café"});
    try expectTokens("x-ray", &.{ "x", "ray" });
}

test "tokenize joiners stay inside a run and never start or end one (S1-T14)" {
    try expectTokens("क्\u{200D}ष a\u{200D} b", &.{ "क्\u{200D}ष", "a", "b" });
    try expectTokens("\u{0BCD}தம்", &.{"தம்"});
    try expectTokens("\u{200C}ab", &.{"ab"});
}

test "tokenize treats letters and digits uniformly across scripts" {
    const allocator = std.testing.allocator;
    const tokens = try tokenize(allocator, "v2 2026 ௨௦௨௬");
    defer freeTokens(allocator, tokens);
    try std.testing.expectEqual(@as(usize, 3), tokens.len);
}

test "tokenize drops variation selectors (S1-T15)" {
    try expectTokens("1\u{FE0F}\u{20E3}", &.{"1"});
    try expectTokens("a\u{FE0F}b", &.{"ab"});
    try expectTokens("\u{845B}\u{E0100} x", &.{ "\u{845B}", "x" });
    try expectTokens("\u{FE0F}ab", &.{"ab"});
}

test "tokenize: decomposed Hangul equals precomposed; CJK compatibility folds (S1-T15)" {
    try expectTokens("\u{1112}\u{1161}\u{11AB}\u{1100}\u{1173}\u{11AF}", &.{"\u{D55C}\u{AE00}"});
    try expectTokens("\u{D55C}\u{AE00}", &.{"\u{D55C}\u{AE00}"});
    try expectTokens("\u{F900}", &.{"\u{8C48}"});
    try expectTokens("\u{212B}ngstrom", &.{"\u{E5}ngstrom"});
}
