//! BM25 cross-language conformance (S1-T1 acceptance criterion 2: "BM25
//! results identical between Python and Zig for both analyzers").
//!
//! `fixtures/bm25-golden.json` (generated by `scripts/gen_bm25_golden.py`,
//! which calls the real `search_platform.core.build_index`/`core.search`)
//! records, per query, the Python-ranked (path, start_line, end_line, score)
//! list. This test natively indexes the same corpora with `indexer.zig`
//! (both `analyzer-v1` and `analyzer-v2` on the ASCII `fixtures/app-text`
//! corpus; `analyzer-v2` only on `fixtures/tamil/passages`, since
//! `analyzer-v1` is ASCII-only by design), queries the published snapshot
//! through `engine.queryTokenized`, and asserts the same top-ranked path AND
//! the same raw per-term BM25 sum (`ranking.lexical.score` in the Python
//! output, `hybrid.Result.lexical_score` in Zig -- not the top-level "score"
//! field, which is the RRF-fused value: `1.0 / (60 + rank)`, the same
//! recurring constant across unrelated queries/corpora since lexical-only
//! mode still runs one channel through reciprocal-rank fusion) within
//! float32-vs-float64 tolerance.
const std = @import("std");
const chunker = @import("chunker.zig");
const hybrid = @import("hybrid.zig");
const indexer = @import("indexer.zig");
const snapshot_open = @import("snapshot_open.zig");

const golden_path = "../fixtures/bm25-golden.json";
const score_tolerance = 1e-4;

fn indexAndOpen(
    arena: std.mem.Allocator,
    io: std.Io,
    source_root: []const u8,
    analyzer: indexer.AnalyzerId,
) !@import("engine.zig").Engine {
    const cwd = std.Io.Dir.cwd();
    var root_dir = try cwd.openDir(io, source_root, .{ .iterate = true });
    defer root_dir.close(io);

    const tmp = std.testing.tmpDir(.{});
    // Intentionally not cleaned up per-call: each call gets a fresh unique
    // tmp dir from the standard library, and the whole process exits when
    // the test binary finishes.
    const report = try indexer.indexFolder(arena, io, root_dir, tmp.dir, analyzer, 1, chunker.default_max_chars, chunker.default_overlap_lines);
    try std.testing.expect(report.documents > 0);
    return snapshot_open.open(arena, io, tmp.dir);
}

fn checkCorpus(
    allocator: std.mem.Allocator,
    io: std.Io,
    source_root: []const u8,
    analyzer: indexer.AnalyzerId,
    queries: std.json.Array,
    identical_out: *usize,
    compared_out: *usize,
) !void {
    var arena_state = std.heap.ArenaAllocator.init(allocator);
    defer arena_state.deinit();
    const arena = arena_state.allocator();

    const opened = try indexAndOpen(arena, io, source_root, analyzer);

    for (queries.items) |query_value| {
        var query_arena_state = std.heap.ArenaAllocator.init(allocator);
        defer query_arena_state.deinit();
        const query_arena = query_arena_state.allocator();

        const entry = query_value.object;
        const query_text = entry.get("query").?.string;
        const ranking = entry.get("ranking").?.array;
        if (ranking.items.len == 0) continue;
        const expected_top = ranking.items[0].object;
        const expected_path = expected_top.get("path").?.string;
        const expected_score = expected_top.get("lexical_score").?.float;

        const score_output = try query_arena.alloc(f32, opened.documents.len);
        const result_output = try query_arena.alloc(hybrid.Result, opened.documents.len);
        const results = try opened.queryTokenized(query_arena, query_text, &.{}, score_output, result_output, .{
            .top_k = opened.documents.len,
            .candidate_k = opened.documents.len,
            .retrieval_mode = .lexical,
        });
        compared_out.* += 1;
        try std.testing.expect(results.len > 0);
        std.testing.expectEqualStrings(expected_path, results[0].path) catch |err| {
            std.debug.print(
                "analyzer={s} query={s}: expected top path {s}, got {s}\n",
                .{ analyzer.label(), query_text, expected_path, results[0].path },
            );
            return err;
        };
        const score_diff = @abs(@as(f64, results[0].lexical_score) - expected_score);
        if (score_diff >= score_tolerance) {
            std.debug.print(
                "analyzer={s} query={s}: expected BM25 {d}, got {d} (diff {d})\n",
                .{ analyzer.label(), query_text, expected_score, results[0].lexical_score, score_diff },
            );
        }
        try std.testing.expect(score_diff < score_tolerance);
        identical_out.* += 1;
    }
}

test "BM25 ranking matches the Python reference for analyzer-v1 and analyzer-v2" {
    const allocator = std.testing.allocator;
    const io = std.testing.io;
    const cwd = std.Io.Dir.cwd();

    var golden_file = cwd.openFile(io, golden_path, .{}) catch |err| switch (err) {
        error.FileNotFound => {
            std.debug.print("skipping: {s} not found (run scripts/gen_bm25_golden.py)\n", .{golden_path});
            return;
        },
        else => return err,
    };
    defer golden_file.close(io);
    const stat = try golden_file.stat(io);
    const size = std.math.cast(usize, stat.size) orelse return error.FileTooBig;
    const golden_bytes = try allocator.alloc(u8, size);
    defer allocator.free(golden_bytes);
    _ = try cwd.readFile(io, golden_path, golden_bytes);

    var parsed = try std.json.parseFromSlice(std.json.Value, allocator, golden_bytes, .{});
    defer parsed.deinit();
    const root_object = parsed.value.object;

    var compared: usize = 0;
    var identical: usize = 0;

    // analyzer-v2 on both corpora (Unicode: the general case).
    try checkCorpus(allocator, io, "../fixtures/app-text", .v2, root_object.get("app_text").?.array, &identical, &compared);
    try checkCorpus(allocator, io, "../fixtures/tamil/passages", .v2, root_object.get("tamil").?.array, &identical, &compared);
    // analyzer-v1 (ASCII) on the ASCII-only corpus, where it must agree with
    // Python's tokenizer exactly (ASCII alnum == Unicode-category alnum on
    // ASCII text, and casefold == lower on ASCII text).
    try checkCorpus(allocator, io, "../fixtures/app-text", .v1, root_object.get("app_text").?.array, &identical, &compared);

    std.debug.print("BM25 conformance: {d} queries compared, {d} identical top-1 (within tolerance)\n", .{ compared, identical });
    try std.testing.expectEqual(compared, identical);
    try std.testing.expect(compared > 0);
}
