//! Golden conformance test (S1-T1 acceptance criterion 1): asserts the Zig
//! `line-window-v1` port in `chunker.zig` reproduces the Python reference
//! (`search_platform.core._line_chunks`/`_chunk_id`) exactly -- same chunk
//! ids, same line ranges, same text -- on every fixture file, including the
//! vendored `fixtures/app-text/` corpus and the invented `fixtures/tamil/`
//! passages.
//!
//! The golden file, `fixtures/chunk-golden.json`, is generated by
//! `scripts/gen_chunk_golden.py`, which imports `search_platform.core`
//! directly and calls its real `_iter_text_files`/`_line_chunks`/`_chunk_id`
//! functions -- so this test compares against the actual Python behavior,
//! not a hand-transcribed copy of it. Regenerate with:
//!   `python3 scripts/gen_chunk_golden.py > fixtures/chunk-golden.json`
const std = @import("std");
const chunker = @import("chunker.zig");

const golden_path = "../fixtures/chunk-golden.json";

test "line-window-v1 chunker matches the Python reference on every fixture file" {
    const allocator = std.testing.allocator;
    const io = std.testing.io;
    const cwd = std.Io.Dir.cwd();

    var golden_file = cwd.openFile(io, golden_path, .{}) catch |err| switch (err) {
        error.FileNotFound => {
            std.debug.print("skipping: {s} not found (run scripts/gen_chunk_golden.py)\n", .{golden_path});
            return;
        },
        else => return err,
    };
    defer golden_file.close(io);
    const stat = try golden_file.stat(io);
    const size = std.math.cast(usize, stat.size) orelse return error.FileTooBig;
    const golden_bytes = try allocator.alloc(u8, size);
    defer allocator.free(golden_bytes);
    _ = try cwd.readFile(io, golden_path, golden_bytes);

    var parsed = try std.json.parseFromSlice(std.json.Value, allocator, golden_bytes, .{});
    defer parsed.deinit();

    const root_object = parsed.value.object;
    try std.testing.expectEqualStrings("line-window-v1", root_object.get("chunker_id").?.string);
    const max_chars: usize = @intCast(root_object.get("max_chars").?.integer);
    const overlap_lines: usize = @intCast(root_object.get("overlap_lines").?.integer);
    try std.testing.expectEqual(chunker.default_max_chars, max_chars);
    try std.testing.expectEqual(chunker.default_overlap_lines, overlap_lines);

    const files = root_object.get("files").?.array;
    var files_compared: usize = 0;
    var chunks_compared: usize = 0;
    var identical_chunks: usize = 0;

    for (files.items) |file_entry| {
        const entry = file_entry.object;
        const root = entry.get("root").?.string;
        const relative_path = entry.get("path").?.string;
        const expected_chunks = entry.get("chunks").?.array;

        var arena_state = std.heap.ArenaAllocator.init(allocator);
        defer arena_state.deinit();
        const arena = arena_state.allocator();

        const full_path = try std.fmt.allocPrint(arena, "../{s}/{s}", .{ root, relative_path });
        const source_stat = try cwd.statFile(io, full_path, .{});
        const source_size = std.math.cast(usize, source_stat.size) orelse return error.FileTooBig;
        const source_buffer = try arena.alloc(u8, source_size);
        const source = try cwd.readFile(io, full_path, source_buffer);

        const spans = try chunker.chunk(arena, source, max_chars, overlap_lines);
        try std.testing.expectEqual(expected_chunks.items.len, spans.len);

        for (spans, expected_chunks.items) |span, expected_value| {
            const expected = expected_value.object;
            var id_hex: [20]u8 = undefined;
            chunker.chunkId(&id_hex, relative_path, span.start_line, span.end_line, span.text);

            try std.testing.expectEqualStrings(expected.get("id").?.string, &id_hex);
            try std.testing.expectEqual(@as(u32, @intCast(expected.get("start_line").?.integer)), span.start_line);
            try std.testing.expectEqual(@as(u32, @intCast(expected.get("end_line").?.integer)), span.end_line);
            try std.testing.expectEqualStrings(expected.get("text").?.string, span.text);
            identical_chunks += 1;
            chunks_compared += 1;
        }
        files_compared += 1;
    }

    std.debug.print(
        "chunk-golden conformance: {d} files, {d} chunks compared, {d} identical\n",
        .{ files_compared, chunks_compared, identical_chunks },
    );
    try std.testing.expect(files_compared > 0);
}
