// Generated by `dart run ffigen --config ffigen.yaml`. Do not edit by hand.
// ignore_for_file: always_specify_types, camel_case_types, non_constant_identifier_names

// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint
import 'dart:ffi' as ffi;

/// Generated FFI bindings for search_simpli.h (Search Simpli's C ABI). Do not edit by hand; see ffigen.yaml.
///
class SearchSimpliBindings {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
      _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  SearchSimpliBindings(ffi.DynamicLibrary dynamicLibrary)
      : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  SearchSimpliBindings.fromLookup(
      ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
          lookup)
      : _lookup = lookup;

  /// The engine contract/build version (contracts/CONTRACTS_VERSION), e.g.
  /// "1.2.0". The returned pointer is static storage owned by the library:
  /// never pass it to ss_free(). Cannot fail.
  ffi.Pointer<ffi.Char> ss_version() {
    return _ss_version();
  }

  late final _ss_versionPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<ffi.Char> Function()>>(
          'ss_version');
  late final _ss_version =
      _ss_versionPtr.asFunction<ffi.Pointer<ffi.Char> Function()>();

  /// A thread-local, null-terminated description of the most recent ss_*
  /// failure on the calling thread ("" if there has been none yet, or after a
  /// call that succeeded does not update it — check the failing call's own
  /// return value first). Valid until this thread's next failing ss_* call.
  /// The returned pointer is thread-local static storage: never pass it to
  /// ss_free(). Cannot fail.
  ffi.Pointer<ffi.Char> ss_last_error() {
    return _ss_last_error();
  }

  late final _ss_last_errorPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<ffi.Char> Function()>>(
          'ss_last_error');
  late final _ss_last_error =
      _ss_last_errorPtr.asFunction<ffi.Pointer<ffi.Char> Function()>();

  /// Open the published snapshot directory at `dir_path` (a null-terminated
  /// path, absolute or relative to the process's current directory) and decode
  /// its current generation into freshly allocated workspaces.
  ///
  /// Returns an opaque handle on success, or NULL on any I/O or validation
  /// failure (missing/corrupt MANIFEST, checksum mismatch, cross-section count
  /// mismatch, out of memory, ...) — see ss_last_error().
  ffi.Pointer<ss_handle> ss_open(
    ffi.Pointer<ffi.Char> dir_path,
  ) {
    return _ss_open(
      dir_path,
    );
  }

  late final _ss_openPtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<ss_handle> Function(ffi.Pointer<ffi.Char>)>>('ss_open');
  late final _ss_open = _ss_openPtr
      .asFunction<ffi.Pointer<ss_handle> Function(ffi.Pointer<ffi.Char>)>();

  /// Free everything ss_open() allocated for `handle`. `handle` may be NULL
  /// (no-op). Do not call any other ss_* function with `handle` afterward, and
  /// do not call ss_close() twice on the same handle.
  void ss_close(
    ffi.Pointer<ss_handle> handle,
  ) {
    return _ss_close(
      handle,
    );
  }

  late final _ss_closePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ss_handle>)>>(
          'ss_close');
  late final _ss_close =
      _ss_closePtr.asFunction<void Function(ffi.Pointer<ss_handle>)>();

  /// Snapshot status as a JSON object: `ready` (bool, always true for a
  /// successfully opened handle), `generation`, `analyzer_id`,
  /// `embedding_model_id`, `vector_dimensions`, `documents`, `terms`,
  /// `postings`.
  ///
  /// Returns a heap-allocated, null-terminated JSON string on success — the
  /// caller must free it with ss_free() — or NULL on failure (out of memory;
  /// see ss_last_error()). `handle` must not be NULL.
  ffi.Pointer<ffi.Char> ss_status(
    ffi.Pointer<ss_handle> handle,
  ) {
    return _ss_status(
      handle,
    );
  }

  late final _ss_statusPtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<ffi.Char> Function(ffi.Pointer<ss_handle>)>>('ss_status');
  late final _ss_status = _ss_statusPtr
      .asFunction<ffi.Pointer<ffi.Char> Function(ffi.Pointer<ss_handle>)>();

  /// Run one query against `handle`'s snapshot.
  ///
  /// query_text    Null-terminated UTF-8 query text. An empty or
  /// punctuation-only query is accepted: it ranks nothing and
  /// reports query_empty_after_analysis (lexical and hybrid).
  /// query_vector  Array of `dims` 32-bit floats, or NULL when `dims` is 0.
  /// Ignored entirely for retrieval_mode "lexical" and for
  /// snapshots with zero vector dimensions (see ss_status()).
  /// Otherwise `dims` must equal the snapshot's vector
  /// dimensions and the vector must be valid, or this call
  /// fails (NULL, ss_last_error()). A valid vector has only
  /// finite components (no NaN, no +-infinity) and a finite L2
  /// norm: the sum of squares, accumulated in float, must not
  /// overflow, which in practice means a norm below about
  /// 1.8e19. An all-zero vector is valid (cosine 0). Lexical
  /// mode does not read the vector, so it does not validate it
  /// either; it still reports vector_ignored.
  /// dims          Length of `query_vector`.
  /// top_k         Final result count, 1-100.
  /// options_json  NULL or "" for defaults, or a null-terminated JSON object
  /// with any of:
  /// "retrieval_mode"    "lexical" | "vector" | "hybrid"
  /// (default "hybrid")
  /// "candidate_k"       integer, default 100, must be
  /// >= top_k and <= 10000
  /// "path_prefix"       string, restricts results to chunks
  /// whose path starts with this prefix
  /// "principal_labels"  array of strings; a chunk is only
  /// returned if the caller holds every
  /// one of its required labels (see
  /// docs/authorization.md)
  /// "profile"           boolean, default false (since
  /// contract 1.2.0); true adds the
  /// `profile` field described below
  ///
  /// Returns a heap-allocated, null-terminated JSON object on success — the
  /// caller must free it with ss_free() — with fields `tool`, `query`, `index`,
  /// `retrieval`, `results` (array of chunk_id/citation/content/score/ranking),
  /// and `answer_policy`. These are exactly the fields of the `result` value a
  /// `search_knowledge` JSON-RPC response carries for the same request
  /// (docs/zig-rpc-service.md), in the same order and byte for byte.
  ///
  /// Since contract 1.2.0 the object ends with three more fields (additive;
  /// removing them gives the 1.1.0 output exactly):
  ///
  /// "warnings"  array, always present, usually empty, of
  /// {"code", "message", "term"?}. Codes:
  /// query_term_unmatched       an analysed query word that was
  /// not found in the searched files. "term" is the
  /// query's own analysed form (lowercased under
  /// ascii-alnum-v1, NFC and case-folded under analyzer-v2),
  /// never the index's spelling. The message is the same
  /// whether the word occurs in no chunk or only in chunks
  /// outside path_prefix or the caller's labels, so the
  /// report does not reveal which hidden files hold a word
  /// (docs/authorization.md). One warning per distinct term,
  /// at its first occurrence, in query order (words not in
  /// the index and words hidden by the scope are
  /// interleaved as they appear). Lexical and hybrid modes
  /// only: vector mode does not use the words.
  /// query_empty_after_analysis the query has no searchable
  /// terms (empty, punctuation, unknown script for the
  /// analyzer). Lexical and hybrid modes only.
  /// vector_ignored             a query vector was passed but
  /// not used: retrieval_mode is "lexical", or the
  /// snapshot stores no vectors.
  /// candidate_depth_cut        a channel produced more
  /// candidates than candidate_k, and the cut can change
  /// the returned list: in hybrid mode when both channels
  /// produced candidates (a hybrid query on a snapshot
  /// without vectors is one channel and does not warn), in
  /// lexical or vector mode, or hybrid, when candidate_k <
  /// top_k (which this function rejects, so it does not
  /// occur there). "lexical" and/or "vector" in the message.
  /// Order of the array: query_empty_after_analysis, then the
  /// query_term_unmatched entries in query order, then
  /// vector_ignored, then candidate_depth_cut.
  /// "request"   {"analyzer_id", "retrieval_mode", "top_k", "candidate_k",
  /// "path_prefix"}: what the engine used, defaults filled in
  /// (path_prefix is null when none).
  /// "profile"   only when options "profile" is true: {"tokenize_us",
  /// "score_us", "rank_us", "serialize_us", "matched_chunks"}.
  /// Microseconds on a monotonic clock; matched_chunks is the
  /// number of chunks inside path_prefix and the caller's labels
  /// holding at least one query term (so a word that only hidden
  /// chunks hold counts 0, like an absent word; 0 in vector mode). serialize_us covers writing the report up to
  /// the "profile" field itself. With "profile" off no clock is
  /// read.
  ///
  /// Returns NULL on failure — invalid top_k/candidate_k, a wrong-sized or
  /// invalid (non-finite or norm-overflowing) query_vector, malformed options_json, or an unknown
  /// retrieval_mode — see ss_last_error(). `handle` must not be NULL.
  ffi.Pointer<ffi.Char> ss_query(
    ffi.Pointer<ss_handle> handle,
    ffi.Pointer<ffi.Char> query_text,
    ffi.Pointer<ffi.Float> query_vector,
    int dims,
    int top_k,
    ffi.Pointer<ffi.Char> options_json,
  ) {
    return _ss_query(
      handle,
      query_text,
      query_vector,
      dims,
      top_k,
      options_json,
    );
  }

  late final _ss_queryPtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<ffi.Char> Function(
              ffi.Pointer<ss_handle>,
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Float>,
              ffi.Size,
              ffi.Size,
              ffi.Pointer<ffi.Char>)>>('ss_query');
  late final _ss_query = _ss_queryPtr.asFunction<
      ffi.Pointer<ffi.Char> Function(
          ffi.Pointer<ss_handle>,
          ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Float>,
          int,
          int,
          ffi.Pointer<ffi.Char>)>();

  /// Look up stored chunks by id. `ids_json` is a null-terminated JSON object:
  ///
  /// {"ids": ["chunk-1", "chunk-2"], "path_prefix": "guides/",
  /// "principal_labels": []}
  ///
  /// `path_prefix` and `principal_labels` are optional and have the same
  /// meaning as `read_chunk`'s parameters of the same name.
  ///
  /// Returns a heap-allocated, null-terminated JSON array on success — the
  /// caller must free it with ss_free() — with one entry per id, in the same
  /// order as `ids`: a chunk object (`chunk_id`, `citation` {path, start_line,
  /// end_line}, `content`) when found and authorized, or
  /// `{"chunk_id": "...", "found": false}` otherwise. Ids are never rejected
  /// individually; the whole call only fails (returns NULL) if `ids_json`
  /// itself is malformed, `ids` is missing, or of out of memory — see
  /// ss_last_error(). `handle` must not be NULL.
  ffi.Pointer<ffi.Char> ss_evidence(
    ffi.Pointer<ss_handle> handle,
    ffi.Pointer<ffi.Char> ids_json,
  ) {
    return _ss_evidence(
      handle,
      ids_json,
    );
  }

  late final _ss_evidencePtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<ffi.Char> Function(
              ffi.Pointer<ss_handle>, ffi.Pointer<ffi.Char>)>>('ss_evidence');
  late final _ss_evidence = _ss_evidencePtr.asFunction<
      ffi.Pointer<ffi.Char> Function(
          ffi.Pointer<ss_handle>, ffi.Pointer<ffi.Char>)>();

  /// Validate the neutral interchange JSON in bytes[0..bytes_len]
  /// (contracts/snapshot-interchange.schema.json) and atomically publish it as
  /// a new generation under `dir_path` (created, including parent directories,
  /// if it does not already exist) — exactly what `searchd import-json` does.
  ///
  /// `analyzer_id` selects how the documents' text is tokenized and is
  /// recorded in the snapshot; queries on it use the same analyzer:
  /// "ascii-alnum-v1"  ASCII letters/digits only, case-insensitive; text in
  /// any other script yields no terms. Unchanged since
  /// contract 1.0.0.
  /// "analyzer-v2"     Unicode (NFC, simple case folding, Unicode letter and
  /// digit categories), since contract 1.1.0. Builds the
  /// same index `searchd index` (and ss_index_folder with
  /// the default analyzer) builds from the same chunks.
  /// Any other value fails with SS_ERR_INVALID_ARGUMENT.
  ///
  /// Returns the published generation number (>= 1) on success, or a negative
  /// ss_error_code (SS_ERR_* above) on failure — see ss_last_error() for the
  /// specific reason (e.g. unsupported analyzer/format version, inconsistent
  /// vector dimensions, a document missing its id/path, a stored vector that is
  /// not valid in the sense of ss_query's query_vector -- a non-finite component
  /// or an L2 norm that overflows float, SS_ERR_INVALID_ARGUMENT with nothing
  /// published -- or an I/O error).
  ///
  /// The payload may carry one optional extra top-level field,
  /// "keep_generations" (integer >= 1, opt-in), with the same meaning as
  /// ss_index_folder's option: after the publish succeeds, section files of
  /// generations older than the newest N are deleted. Absent: nothing is
  /// deleted. 0 returns SS_ERR_INVALID_ARGUMENT.
  int ss_import_json(
    ffi.Pointer<ffi.Char> dir_path,
    ffi.Pointer<ffi.Char> bytes,
    int bytes_len,
  ) {
    return _ss_import_json(
      dir_path,
      bytes,
      bytes_len,
    );
  }

  late final _ss_import_jsonPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int64 Function(ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>,
              ffi.Size)>>('ss_import_json');
  late final _ss_import_json = _ss_import_jsonPtr.asFunction<
      int Function(ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>, int)>();

  /// Free a pointer previously returned by ss_status(), ss_query(), or
  /// ss_evidence(). `ptr` may be NULL (no-op). Never call this on the result
  /// of ss_version() or ss_last_error() (both static storage, not caller-owned).
  void ss_free(
    ffi.Pointer<ffi.Char> ptr,
  ) {
    return _ss_free(
      ptr,
    );
  }

  late final _ss_freePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Char>)>>(
          'ss_free');
  late final _ss_free =
      _ss_freePtr.asFunction<void Function(ffi.Pointer<ffi.Char>)>();

  /// Index the folder at `folder_path` and atomically publish (or
  /// re-publish/update) a lexical-only snapshot into `dir_path` (created,
  /// including parent directories, if it does not already exist) — the
  /// native-engine equivalent of `searchd index` / `searchd index --update`.
  ///
  /// This call mutates the directory identified by `dir_path` rather than
  /// operating on an already-open ss_handle: indexing publishes a *new*
  /// generation, and a handle is a decoded snapshot of one already-published
  /// generation, so there is nothing for an open handle to do here that
  /// closing and reopening afterward (ss_close then ss_open) does not already
  /// cover — do that to see the new generation through a handle.
  ///
  /// dir_path      Snapshot directory to publish/update (created if
  /// missing).
  /// folder_path    Folder to index.
  /// opts_json      NULL or "" for defaults, or a null-terminated JSON
  /// object with any of:
  /// "analyzer"          "analyzer-v1"/"v1" or
  /// "analyzer-v2"/"v2" (default),
  /// same spelling as `searchd index
  /// --analyzer`
  /// "max_chars"         chunker max characters per chunk
  /// (default 1600)
  /// "overlap_lines"     chunker overlap lines (default 3)
  /// "update"            bool, default false. false: full
  /// rebuild, always publishing the
  /// next free generation in
  /// `dir_path` (never fails with
  /// PathAlreadyExists on a directory
  /// that already holds a snapshot).
  /// true: incremental update —
  /// per-file content hashes (persisted
  /// in `dir_path`/INDEX-STATE.json)
  /// skip unchanged files, deleted
  /// files are tombstoned. Fails
  /// closed (see below) if `dir_path`
  /// already holds a snapshot published
  /// with a different analyzer.
  /// "max_file_bytes"    per-file size cap in bytes
  /// (default 10 MiB); a larger file is
  /// never read and is excluded,
  /// counted under the report's
  /// "too_large"
  /// "max_total_bytes"   total bytes read in one call
  /// before remaining unprocessed files
  /// are left untouched for this
  /// generation (default 512 MiB)
  /// "keep_generations"  integer >= 1, opt-in. After a
  /// successful publish, delete the
  /// section files of generations older
  /// than the newest N (the current
  /// generation is always kept; so are
  /// MANIFEST, WRITER.LOCK and
  /// INDEX-STATE.json). Absent: nothing
  /// is deleted. 0 is an error. A failed
  /// deletion never fails the call; the
  /// report then carries "pruned_files"
  /// and "prune_failures" (integers,
  /// present only when this option is
  /// set). Close handles on a pruned
  /// generation first if they matter to
  /// you: see docs/generation-lifecycle.md.
  ///
  /// Returns a heap-allocated, null-terminated JSON report object on success —
  /// the caller must free it with ss_free() — with fields "generation"
  /// (integer), "analyzer_id" (string), "added", "changed", "removed",
  /// "unchanged", "budget_exhausted", "too_large", "unreadable" (all
  /// integers), "too_large_paths", "unreadable_paths" (arrays of the relative
  /// paths counted under "too_large"/"unreadable" — never just a bare count),
  /// "documents", "terms", "postings" (all integers). A non-"update" run
  /// always reports "changed"/"removed"/"unchanged" as 0 (a full rebuild never
  /// compares against a previous generation); an "update" run additionally
  /// reports "changed"/"removed". max_file_bytes/max_total_bytes are enforced
  /// on a non-"update" run exactly as on an "update" run (S1-T5), so
  /// "too_large"/"too_large_paths"/"budget_exhausted" can be nonzero either
  /// way — "added" only counts the files a non-"update" run actually indexed.
  /// "unchanged" and "budget_exhausted" are reported separately — "nothing to
  /// do" and "left for a later run because max_total_bytes ran out" are never
  /// the same number. An empty folder_path, or a folder whose last indexable
  /// file was just deleted, publishes an empty generation (0
  /// documents/terms/postings) instead of failing.
  ///
  /// With "update": true, if MANIFEST exists but a section file it names is
  /// missing or unreadable, the update does not trust INDEX-STATE.json: it
  /// re-indexes every file, publishes a full next generation, and the report
  /// carries "recovered": "missing_section" (the field is absent otherwise).
  /// With no MANIFEST but an INDEX-STATE.json present, the state is likewise
  /// not trusted: the update re-indexes every file and reports
  /// "recovered": "missing_manifest".
  ///
  /// A file larger than max_file_bytes is tombstoned, not silently kept: it is
  /// counted (and named) under "too_large"/"too_large_paths", and its
  /// previously indexed chunks (if any) are dropped from this generation. A
  /// file that is merely unreadable this run (permissions, a transient I/O
  /// error, invalid UTF-8) keeps its previously indexed chunks instead — see
  /// docs/incremental-indexing.md.
  ///
  /// Returns NULL on failure — a missing/unreadable folder_path, an
  /// unrecognized "analyzer", or (with "update": true) `dir_path` already
  /// holding a snapshot published with a different analyzer — see
  /// ss_last_error().
  ffi.Pointer<ffi.Char> ss_index_folder(
    ffi.Pointer<ffi.Char> dir_path,
    ffi.Pointer<ffi.Char> folder_path,
    ffi.Pointer<ffi.Char> opts_json,
  ) {
    return _ss_index_folder(
      dir_path,
      folder_path,
      opts_json,
    );
  }

  late final _ss_index_folderPtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<ffi.Char> Function(
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>)>>('ss_index_folder');
  late final _ss_index_folder = _ss_index_folderPtr.asFunction<
      ffi.Pointer<ffi.Char> Function(ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>)>();
}

final class ss_handle extends ffi.Opaque {}

const int SS_ERR_INVALID_ARGUMENT = -1;

const int SS_ERR_IO = -2;

const int SS_ERR_CORRUPT_SNAPSHOT = -3;

const int SS_ERR_CAPACITY = -4;

const int SS_ERR_OUT_OF_MEMORY = -5;

const int SS_ERR_NOT_FOUND = -6;

const int SS_ERR_INTERNAL = -7;
